'use strict';
// Optional real-browser acceptance test; runtime application has no npm dependencies.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('node:assert/strict'),{spawn}=require('child_process');
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'uk-browser-')),port=18989,base=`http://127.0.0.1:${port}`;
const env={...process.env,NODE_ENV:'test',HOST:'127.0.0.1',PORT:String(port),DB_FILE:path.join(tmp,'app.db'),UPLOAD_DIR:path.join(tmp,'uploads'),OWNER_LOGIN:'owner',OWNER_PASSWORD:'Browser-Acceptance-Only!'};
const server=spawn(process.execPath,['server.js'],{cwd:root,env,stdio:'ignore'});
let browser;const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{try{
 for(let n=0;n<50;n++){try{if((await fetch(base+'/healthz')).ok)break;}catch{}await pause(100);}
 const auth=await fetch(base+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'owner',password:env.OWNER_PASSWORD})});const data=await auth.json(),headers={'content-type':'application/json',cookie:auth.headers.get('set-cookie').split(';')[0],'x-csrf-token':data.csrf};
 const post=async(url,body)=>{const r=await fetch(base+url,{method:'POST',headers,body:JSON.stringify(body)});assert.ok(r.ok,url+': '+r.status);return r.json();};
 const building=await post('/api/buildings',{name:'Торговый комплекс с очень длинным названием для проверки мобильной карточки',address:'Санкт-Петербург, длинный адрес, 136',area:1000,occupied:700});
 const secondBuilding=await post('/api/buildings',{name:'Второй объект',address:'Москва',area:500,occupied:200});
 await post('/api/tenants',{buildingId:building.id,company:'Тестовый арендатор',area:100,unit:'101'});
 const worker=(await post('/api/staff',{name:'Работник с длинной фамилией',email:'worker',password:'Browser-Worker-Only!',role:'technician',buildingIds:[building.id]})).user;
 for(let n=0;n<8;n++)await post('/api/issues',{buildingId:building.id,title:'Работа '+n,responsibleUserId:worker.id,due:'2020-01-01'});
 browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE:',e.message);});page.on('dialog',d=>d.accept());
 await page.goto(base);await page.locator('[name="email"]').fill('owner');await page.locator('[name="password"]').fill(env.OWNER_PASSWORD);await page.locator('#loginForm button[type="submit"]').click();await page.locator('#pageTitle').waitFor();
 const screenshots=process.env.SCREENSHOT_DIR;if(screenshots)fs.mkdirSync(screenshots,{recursive:true});
 assert.equal(await page.locator('.mobile-nav [data-view]').count(),4,'only four primary destinations');
 assert.equal(await page.locator('[data-view="tasks"]').count(),0,'no duplicate task section');
 if(screenshots)await page.screenshot({path:path.join(screenshots,'today-390.png'),fullPage:true});
 // Object links must filter real records and preselect the object in new forms.
 await page.locator('[data-view="buildings"]:visible').click();await page.locator(`[data-building="${secondBuilding.id}"]`).click();await page.locator('[data-object-view="tenants"]').click();
 assert.equal(await page.locator('[data-tenant]').count(),0,'second object does not show tenants of the first');
 await page.locator('#newTenant').click();await page.waitForFunction(()=>document.querySelector('#tenantForm')?.dataset.restoring==='');assert.equal(await page.locator('#tenantForm [name="buildingId"]').inputValue(),secondBuilding.id);await page.locator('#modal [data-close]').first().click();
 await page.locator('#backToBuilding').click();await page.locator('[data-object-view="equipment"]').click();await page.locator('#newEquipment').click();await page.waitForFunction(()=>document.querySelector('#equipmentForm')?.dataset.restoring==='');assert.equal(await page.locator('#equipmentForm [name="buildingId"]').inputValue(),secondBuilding.id);await page.locator('#modal [data-close]').first().click();
 await page.locator('#backToBuilding').click();await page.locator('[data-object-view="expenses"]').click();await page.locator('#newExpense').click();await page.waitForFunction(()=>document.querySelector('#expenseForm')?.dataset.restoring==='');assert.equal(await page.locator('#expenseForm [name="buildingId"]').inputValue(),secondBuilding.id);await page.locator('#modal [data-close]').first().click();
 await page.locator('#clearScope').click();assert.equal(await page.locator('#expenseBuildingFilter').inputValue(),'');
 await page.locator('[data-view="buildings"]:visible').click();await page.locator('#addBuilding').click();await page.waitForFunction(()=>document.querySelector('#buildingForm')?.dataset.restoring==='');
 assert.equal(await page.locator('#buildingForm [name="occupied"]').isVisible(),false,'optional fields initially collapsed');
 await page.locator('#buildingForm [name="name"]').fill('Проверка обязательности');
 await page.locator('#buildingForm [name="occupied"]').evaluate(e=>e.value='-1');await page.locator('#buildingForm [type="submit"]').click();assert.equal(await page.locator('#buildingForm details').getAttribute('open'),'','invalid optional field opens its section');await page.locator('#modal [data-close]').first().click();
 for(const width of [320,390,1280]){
  await page.setViewportSize({width,height:844});await page.locator('[data-view="buildings"]:visible').click();await page.locator('#buildingSearch').fill('торговый');assert.equal(await page.locator('#buildingResults .building-card').count(),1);await page.locator('#buildingSearch').fill('');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflow at '+width);
  for(const button of await page.locator('#buildingResults .building-actions .btn').all()){await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width+1,'clipped object button at '+width);}
  await page.evaluate(()=>window.scrollTo(0,0));if(screenshots)await page.screenshot({path:path.join(screenshots,`objects-${width}.png`),fullPage:true});
  await page.locator(`[data-building="${building.id}"]`).click();assert.equal(await page.locator('#modal [data-issue]').count(),8);if(screenshots)await page.screenshot({path:path.join(screenshots,`detail-${width}.png`)});await page.locator('#buildingTask').scrollIntoViewIfNeeded();const taskBox=await page.locator('#buildingTask').boundingBox();assert.ok(taskBox.x>=0&&taskBox.x+taskBox.width<=width+1);await page.locator('#modal [data-close]').first().click();
 }
 await page.setViewportSize({width:390,height:844});await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="admin"]').click();await page.locator('.staff-table').waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'admin overflow');if(screenshots)await page.screenshot({path:path.join(screenshots,'staff-390.png'),fullPage:true});
 await page.locator('[data-view="buildings"]:visible').click();await page.locator('.building-toolbar summary').click();await page.locator('#buildingInspection').click();assert.equal(await page.locator('[data-check-tenant]').count(),1,'first object tenant loads automatically');
 const photo={name:'photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jP1sAAAAASUVORK5CYII=','base64')};
 for(const n of [1,2,3])await page.locator('#exterior'+n).setInputFiles(photo);
 console.log('Browser: layouts checked; submitting inspection');await page.locator('#inspectionForm [type="submit"]').click();await page.locator('#inspectionForm').waitFor({state:'detached'});
 await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="admin"]').click();
 await page.locator('[data-edit-staff]').click();await page.locator('#staffForm [name="name"]').fill('Работник после изменения');await page.locator('#staffForm [type="submit"]').click();await page.locator('#staffForm').waitFor({state:'detached'});assert.ok((await page.locator('.staff-table').textContent()).includes('Работник после изменения'));
 await page.locator('[data-reset-staff]').click();await page.locator('#staffPasswordForm [name="password"]').fill('Browser-New-Password!');await page.locator('#staffPasswordForm [type="submit"]').click();await page.locator('#staffPasswordForm').waitFor({state:'detached'});
 await page.locator('[data-view="buildings"]:visible').click();await page.locator(`[data-building="${building.id}"]`).click();await page.locator('#buildingTask').click();await page.locator('#issueForm input[name="title"]').fill('Черновик после потери связи');await page.locator('#issuePhotos').setInputFiles(photo);await page.waitForFunction(()=>document.querySelector('#issueForm [data-draft-status]')?.dataset.state==='ready');
 console.log('Browser: testing offline photo draft');await context.setOffline(true);await page.locator('#issueForm [type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#issueForm')?.dataset.busy!=='1');assert.equal(await page.locator('#issueForm input[name="title"]').inputValue(),'Черновик после потери связи');
 await context.setOffline(false);await page.reload();await page.locator('#pageTitle').waitFor();await page.locator('[data-view="buildings"]:visible').click();await page.locator(`[data-building="${building.id}"]`).click();await page.locator('#buildingTask').click();await page.waitForFunction(()=>document.querySelector('#issueForm input[name="title"]').value==='Черновик после потери связи');
 assert.equal(await page.locator('#issuePhotos').evaluate(e=>e.files.length),1,'selected photo survives reload');assert.equal(await page.locator('#issuePhotos').evaluate(e=>e.files[0].name),'photo.png');

 await page.locator('#issueForm [type="submit"]').click();await page.locator('#issueForm').waitFor({state:'detached'});const issues=await(await fetch(base+'/api/issues',{headers})).json();assert.equal(issues.filter(x=>x.title==='Черновик после потери связи').length,1);assert.equal(issues.find(x=>x.title==='Черновик после потери связи').photos.length,1);
 // A confirmed send clears both draft text and private photo blobs.
 await page.locator(`[data-building="${building.id}"]`).click();await page.locator('#buildingTask').click();await page.waitForFunction(()=>document.querySelector('#issueForm')?.dataset.restoring==='');assert.equal(await page.locator('#issueForm [name="title"]').inputValue(),'');assert.equal(await page.locator('#issuePhotos').evaluate(e=>e.files.length),0);
 // Storage failure must be visible without preventing an online submission.
 await page.evaluate(()=>{window.originalDraftPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('full','QuotaExceededError');};});
 await page.locator('#issueForm [name="title"]').fill('Сбой локального хранилища');await page.locator('#issuePhotos').setInputFiles(photo);await page.waitForFunction(()=>document.querySelector('#issueForm [data-draft-status]')?.dataset.state==='error');assert.equal(await page.locator('#issuePhotos').evaluate(e=>e.files.length),1);await page.locator('#issueForm [type="submit"]').click();await page.locator('#issueForm').waitFor({state:'detached'});await page.evaluate(()=>{IDBObjectStore.prototype.put=window.originalDraftPut;delete window.originalDraftPut;});
 await page.locator(`[data-building="${building.id}"]`).click();await page.locator('#buildingTask').click();await page.locator('#issueForm [name="title"]').fill('Ответ сервера потерян');
 await page.route('**/api/issues',async route=>{if(route.request().method()==='POST'){await route.fetch();await route.abort('failed');}else await route.continue();});
 await page.locator('#issueForm [type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#issueForm')?.dataset.busy!=='1');await page.unroute('**/api/issues');
 await page.locator('#issueForm [type="submit"]').click();await page.locator('#issueForm').waitFor({state:'detached'});const retried=await(await fetch(base+'/api/issues',{headers})).json();assert.equal(retried.filter(x=>x.title==='Ответ сервера потерян').length,1);
 console.log('Browser: checking tenant/expenses forms');
 // Tenant details stay linked after editing; expenses are editable at mobile widths.
 await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="tenants"]').click();await page.locator('[data-tenant]').first().click();await page.locator('#editTenant').click();await page.locator('#tenantForm [name="company"]').fill('Арендатор после редактирования');await page.waitForFunction(()=>document.querySelector('#tenantForm [data-draft-status]')?.dataset.state==='ready');await page.locator('#tenantForm summary').click();await page.locator('#tenantForm [name="phone"]').fill('+7 000 123');await page.locator('#tenantForm [type="submit"]').click();await page.locator('#tenantForm').waitFor({state:'detached'});assert.ok((await page.locator('#modal').textContent()).includes('Арендатор после редактирования'));await page.locator('#modal [data-close]').first().click();
 await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="expenses"]').click();await page.locator('#newExpense').click();await page.locator('#expenseForm [name="electricity"]').fill('1500.25');await page.locator('#expenseForm [name="repair"]').fill('99.75');assert.ok((await page.locator('#expenseTotal').textContent()).replace(/\s/g,'').includes('1600'));await page.locator('#expenseForm [type="submit"]').click();await page.locator('#expenseForm').waitFor({state:'detached'});assert.equal(await page.locator('.expense-card').count(),1);await page.locator('[data-edit-expense]').click();await page.locator('#expenseForm [name="repair"]').fill('199.75');await page.locator('#expenseForm [type="submit"]').click();await page.locator('#expenseForm').waitFor({state:'detached'});
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'expenses overflow at '+width);for(const button of await page.locator('.expense-card button').all()){await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width+1);}if(screenshots)await page.screenshot({path:path.join(screenshots,`expenses-${width}.png`),fullPage:true});}
 await page.locator('[data-delete-expense]').click();await page.locator('.expense-card').waitFor({state:'detached'});
 console.log('Browser: checking equipment and monthly resources');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="equipment"]').click();await page.locator('#newEquipment').click();await page.locator('#equipmentForm [name="name"]').fill('Насосная установка с длинным названием');await page.waitForFunction(()=>document.querySelector('#equipmentForm [data-draft-status]')?.dataset.state==='ready');await page.locator('#equipmentForm summary').click();assert.equal(await page.locator('#equipmentForm details').evaluate(e=>e.open),true);await page.locator('#equipmentForm [name="model"]').fill('LongModelWithoutSpaces123456789012345678901234567890');await page.locator('#equipmentForm [name="location"]').fill('Подвал, техническое помещение');await page.locator('#equipmentForm [name="nextService"]').fill('2020-01-01');await page.locator('#equipmentForm [type="submit"]').click();await page.locator('#equipmentForm').waitFor({state:'detached'});
 await page.locator('#equipmentSearch').fill('Насос');assert.equal(await page.locator('[data-equipment]').count(),1);await page.locator('#equipmentState').selectOption('due');assert.equal(await page.locator('[data-equipment]').count(),1);
 await page.locator('[data-edit-equipment]').click();await page.locator('#equipmentForm [name="status"]').selectOption('attention');await page.locator('#equipmentForm [type="submit"]').click();await page.locator('#equipmentForm').waitFor({state:'detached'});
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'equipment overflow at '+width);const titleBox=await page.locator('#pageTitle').boundingBox(),actionsBox=await page.locator('.top-actions').boundingBox();assert.ok(titleBox.x+titleBox.width<=actionsBox.x,'header title overlaps controls');await page.evaluate(()=>window.scrollTo(0,0));if(screenshots)await page.screenshot({path:path.join(screenshots,`equipment-${width}.png`),fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.locator('#notificationsBtn').click();await page.locator('[data-notify-equipment]').click();assert.ok((await page.locator('#modal').textContent()).includes('Насосная установка'));await page.locator('#equipmentDelete').click();await page.locator('[data-equipment]').waitFor({state:'detached'});
 await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="metrics"]').click();
 for(const [month,value] of [['2026-08','100'],['2026-09','125']]){await page.locator('#newMetric').click();await page.locator('#metricsForm [name="month"]').fill(month);await page.locator('#metricsForm [name="electricity"]').fill(value);await page.locator('#metricsForm [name="water"]').fill('10.125');await page.locator('#metricsForm [name="heat"]').fill('0');await page.locator('#metricsForm [type="submit"]').click();await page.locator('#metricsForm').waitFor({state:'detached'});}
 assert.ok((await page.locator('#metricResults').textContent()).includes('+25%'));await page.locator('#metricResource').selectOption('water');assert.equal(await page.locator('.metric-progress').count(),2);await page.locator('#metricBuilding').selectOption(secondBuilding.id);assert.equal(await page.locator('[data-edit-metric]').count(),0);await page.locator('#metricBuilding').selectOption(building.id);await page.locator('[data-edit-metric]').first().click();await page.locator('#metricsForm [name="electricity"]').fill('150');await page.locator('#metricsForm [type="submit"]').click();await page.locator('#metricsForm').waitFor({state:'detached'});assert.ok((await page.locator('#metricResults').textContent()).includes('+50%'));
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'metrics overflow at '+width);for(const button of await page.locator('#metricResults button').all()){await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width+1);}await page.evaluate(()=>window.scrollTo(0,0));if(screenshots)await page.screenshot({path:path.join(screenshots,`metrics-${width}.png`),fullPage:true});}
 await page.locator('[data-delete-metric]').first().click();await page.waitForFunction(()=>document.querySelectorAll('[data-delete-metric]').length===1);
 await post('/api/staff',{name:'Инспектор второго объекта',email:'inspector',password:'Browser-Inspector-Only!',role:'inspector',buildingIds:[secondBuilding.id]});
 await page.setViewportSize({width:390,height:844});await page.locator('#refreshBtn').click();await page.locator('[data-view="settings"]:visible').click();await page.locator('[data-menu-view="admin"]').click();await page.locator('details summary').filter({hasText:'Распределение заданий'}).click();await page.locator(`[data-plan="${building.id}"]`).click();assert.ok(!(await page.locator('#planForm [name="inspectorUserId"]').textContent()).includes('Инспектор второго объекта'));assert.ok(!(await page.locator('#planForm [name="inspectorUserId"]').textContent()).includes('Работник после изменения'));await page.locator('#modal [data-close]').first().click();await page.locator(`[data-plan="${secondBuilding.id}"]`).click();assert.ok((await page.locator('#planForm [name="inspectorUserId"]').textContent()).includes('Инспектор второго объекта'));await page.locator('#modal [data-close]').first().click();
 // Logout clears the owner's locally retained photo draft.
 await page.locator('[data-view="buildings"]:visible').click();await page.locator(`[data-building="${building.id}"]`).click();await page.locator('#buildingTask').click();await page.locator('#issueForm [name="title"]').fill('Приватный черновик владельца');await page.locator('#issuePhotos').setInputFiles(photo);await page.waitForFunction(()=>document.querySelector('#issueForm [data-draft-status]')?.dataset.state==='ready');await page.locator('#modal [data-close]').first().click();await page.locator('[data-view="settings"]:visible').click();await page.locator('#logoutMobile').click();await page.locator('#loginForm').waitFor();
 const remaining=await page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('owner-property-drafts',1);r.onsuccess=()=>{const request=r.result.transaction('drafts').objectStore('drafts').getAll();request.onsuccess=()=>resolve(request.result.filter(x=>x.key.startsWith('owner-draft:u-owner:')).length);request.onerror=reject;};r.onerror=reject;}));assert.equal(remaining,0,'logout deletes private drafts');
 const staffContext=await browser.newContext({viewport:{width:390,height:844}}),staffPage=await staffContext.newPage();staffPage.on('pageerror',e=>errors.push(e.message));await staffPage.goto(base);await staffPage.locator('[name="email"]').fill('worker');await staffPage.locator('[name="password"]').fill('Browser-New-Password!');await staffPage.locator('#loginForm [type="submit"]').click();await staffPage.locator('#pageTitle').waitFor();assert.equal(await staffPage.locator('[data-view="admin"]').count(),0);assert.equal((await staffContext.request.get(base+'/api/admin')).status(),403);
 assert.equal(await staffPage.locator('#view [data-issue]').count(),6,'home shows a short list of own assignments');
 if(screenshots)await staffPage.screenshot({path:path.join(screenshots,'worker-390.png'),fullPage:true});
 await staffPage.locator('#allTasks').click();assert.equal(await staffPage.locator('#onlyMine').isChecked(),true);assert.equal(await staffPage.locator('#taskResults [data-issue]').count(),8);
 await staffPage.locator('#taskSearch').fill('Работа 0');assert.equal(await staffPage.locator('#taskResults [data-issue]').count(),1);await staffPage.locator('#taskResults [data-issue]').click();
 await staffPage.locator('#startIssue').click();await staffPage.locator('#startIssue').waitFor({state:'detached'});assert.ok((await staffPage.locator('#modal').textContent()).includes('В работе'));
 await staffPage.locator('#quickSolve').click();await staffPage.locator('#reportForm [name="text"]').fill('Работа выполнена, результат проверен');await staffPage.locator('#reportPhotos').setInputFiles(photo);await staffPage.locator('#reportForm [type="submit"]').click();await staffPage.locator('#reportForm').waitFor({state:'detached'});
 assert.ok((await staffPage.locator('#modal').textContent()).includes('Выполнена'));await staffPage.locator('#modal [data-close]').first().click();
 await staffPage.locator('[data-view="issues"]:visible').click();await staffPage.locator('[data-task-state="done"]').click();assert.equal(await staffPage.locator('#taskResults [data-issue]').count(),1,'completed work remains accessible');
 if(await staffPage.locator('[data-view="equipment"]:visible').count())await staffPage.locator('[data-view="equipment"]:visible').click();else{await staffPage.locator('[data-view="settings"]:visible').click();await staffPage.locator('[data-menu-view="equipment"]').click();}assert.equal(await staffPage.locator('#newEquipment').count(),0,'staff viewing registry cannot edit without an explicit permission');
 assert.deepEqual(errors,[]);console.log('Browser: 320/390/1280 layouts, staff menu, offline photo restoration, tenant/expense CRUD, equipment, metrics and maintenance navigation: OK');
 }finally{await browser?.close();server.kill('SIGTERM');}})().catch(e=>{console.error(e.stack);process.exitCode=1});
